In [1]:
import numpy as np

In [2]:
arr = np.arange(11,31)
print(arr)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [3]:
print(arr[1]) # to get a single element from array

12


In [4]:
print(arr[1:5]) # slice the array from index 0 to 5 - 1 = 4
print(arr[:10]) # slice from index 0 to 9
print(arr[:]) # slice from index 0 to last element

[12 13 14 15]
[11 12 13 14 15 16 17 18 19 20]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [6]:
#numpy slicing from 2d arrays
#first we will reshape the elements
a = arr.reshape(4,5)
print(a)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [8]:
# to get a single row sliced out
row = a[1]
print(row)



[16 17 18 19 20]


In [9]:
# to get another 2d vector sliced from it, first extract the row, then the column
matrix = a[2:4,1:3]
print(matrix)

[[22 23]
 [27 28]]


In [10]:
#to get a single element
a[1,2]
print(a[1,2])

18


In [ ]:
#boolean indexing
bool_index = arr % 2 == 0 # returns array of same size , but true whenever the element is even and vice versa
b =arr[bool_index] # has only the elements for which the bool_index is true i.e. the even elements
print(b)

[12 14 16 18 20 22 24 26 28 30]
