In [1]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4]) # array of same data type
print(arr)

[1 2 3 4]


In [3]:
a = [1,2,3.4,'hello']
print(a) # this is the python inbuilt list for python, can store data for all data types

[1, 2, 3.4, 'hello']


In [ ]:
np.array(a) #typecasting the array to list, it wont throw
#any error, will simply change all the data types to string 
#to keep the definition of array

array(['1', '2', '3.4', 'hello'], dtype='<U32')

In [6]:
#lists do not support multidimensions but arrays do
l = [[1,2,3],[4,5,6],[7,8,9]]
print(l)
print(np.array(l))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
