In [1]:
import numpy as np


In [ ]:
arr = np.arange(1,10) #range of numbers is from 1 to 9
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.arange(1,11,2)# range is from 1 to 10, but with step size of 2
print(arr)

[1 3 5 7 9]


In [5]:
arr = np.zeros(6)
print(arr)

[0. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.zeros((6,6))#prints 6 X 6 matrix with zeros
print(arr)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
arr = np.ones(6) # print 6 ones
print(arr)

[1. 1. 1. 1. 1. 1.]


In [ ]:
arr = np.linspace(1,5,10) # elements from 1 to 2, but only n equispaced elements
print(arr)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
