In [1]:
import numpy as np

In [2]:
#deep copy is when u slice an array and if u update it the original array doesnt get affected
a = np.array([1,2,3])
b = a.copy() # makes a deep copy
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [ ]:
#shallow copy is when tha chnages in new arrray is reflected in the original one
a = np.array([1, 2, 3, 4])
b = a.view()   # shallow copy (view)

b[0] = 100

print(a)
print(b)

[100   2   3   4]
[100   2   3   4]
