In [1]:
import numpy as np

In [5]:
a = np.arange(1,17).reshape((2,8))
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [6]:
b = np.arange(1,17).reshape((8,2))
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [ ]:
a@b #mat multiplication
np.dot(a,b) # both are same

array([[372, 408],
       [884, 984]])

In [8]:
a.T #transpose

array([[ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15],
       [ 8, 16]])