In [8]:
import numpy as np

In [9]:
arr = np.random.randint(10,20,10)
print(arr)

[10 12 14 16 15 15 17 18 17 12]


In [14]:
arr.reshape((5,2)) # reshapes given array into 5 X 2 matrix, the no. of elements should be compatible
print(arr) #only printing this wont change the array
a = arr.reshape((5,2)) #resizing  a matrix nothing new
print(a)

[10 12 14 16 15 15 17 18 17 12]
[[10 12]
 [14 16]
 [15 15]
 [17 18]
 [17 12]]
