In [1]:
import numpy as np

In [2]:
#stacking only happens between vectors, not matrices
a = np.arange(1,5)
b = np.arange(5,9)
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [4]:
#three types of stack

#1. horizontal stack
np.hstack((a,b))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
#vertical stack
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
#column stack
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])